### ISSUE TITLE
Transaction check error

### ISSUE THREAD

**Issue by rcla** [schnitzeltony/meta-mortsgna#11]
I am building xfce4-base-image for raspberry pi 3.

But it is failing in the do_rootfs stage.

`Error: Transaction check error:
  file /etc/polkit-1/rules.d conflicts between attempted installs of polkit-group-rule-datetime-1.0-r0.cortexa7t2hf_neon_vfpv4 and polkit-0.115-r0.cortexa7t2hf_neon_vfpv4
`

`ERROR: xfce4-base-image-1.0-r0 do_rootfs: Function failed: do_rootfs`

I have changed from master branch to thud, but still with the same issue.

[log.do_rootfs.log](https://github.com/schnitzeltony/meta-mortsgna/files/3697214/log.do_rootfs.log)

**Comment by schnitzeltony** [comment]
That is unrelated to meta-mortsgna but interesting anyway - if I remember correctly it is package-manager rpm (personally I sill use opkg) which is more picky: As soon as two recipes try to install same path with different user privileges it complains. We had something similar in meta-openembedded but I do not remember exactly and need to analyse what it was and how it was solved. Will come back then.

**Comment by schnitzeltony** [comment]
Cannot attach a patch because I do not know what version of meta-openembedded you are using currently.

So please try in meta-openembedded / in the file:

'meta-oe/recipes-extended/polkit/polkit-group-rule.inc' change the line:

>chown polkitd:polkitd ${D}${sysconfdir}/polkit-1/rules.d

to 

>chown polkitd:root ${D}/${sysconfdir}/polkit-1/rules.d

Please report results because if it fixes the error, I will send out a patch to meta-openembedded

**Comment by rcla** [comment]
I had to format the PC and reinstall the operating system.

So I had to start from scratch ...
Before I start building the image, I will make the change you say.
When I finish I will publish my results.

**Comment by schnitzeltony** [comment]
Uuh - sh.. happens

**Comment by rcla** [comment]
With the change you proposed, it worked!

Thank you very much for your help.

**Comment by schnitzeltony** [comment]
FWIW: Patch sent to meta-openembedded [1]

[1] http://lists.openembedded.org/pipermail/openembedded-devel/2019-October/202135.html
