### ISSUE TITLE
kde ? plasma? or kde deskop

### ISSUE THREAD

**Issue by outbackdingo** [schnitzeltony/meta-mortsgna#14]
is this kde plasma? or kde deskop ?

**Comment by schnitzeltony** [comment]
This is a distro layer. What is the issue exactly?

**Comment by outbackdingo** [comment]
im trying to get kde-plasma desktop installed, or maybe i should ask how do i get any desktop installed

**Comment by schnitzeltony** [comment]
Add at least [meta-qt5](https://layers.openembedded.org/layerindex/branch/master/layer/meta-qt5/) and [meta-qt5-extra](https://layers.openembedded.org/layerindex/branch/master/layer/meta-qt5-extra/) to your layers and add [plasma-world](https://github.com/schnitzeltony/meta-qt5-extra/blob/master/recipes-kde/packagegroups/plasma-world.bb) to your image. When using this layer you can simply build a plasma desktop image by `bitbake kde-base-image`
