### ISSUE TITLE
tremor src_uri changed

### ISSUE THREAD

**Issue by outbackdingo** [schnitzeltony/meta-mortsgna#15]
SRC_URI = "git://gitlab.xiph.org/xiph/tremor.git;protocol=https \
           file://obsolete_automake_macros.patch;striplevel=0 \
           file://tremor-arm-thumb2.patch \
"

**Comment by schnitzeltony** [comment]
This is an issue of [meta-openembedded layer](https://github.com/openembedded/meta-openembedded). Please report the error in the [mailinglist](https://lists.openembedded.org/g/openembedded-devel) - it helps to append logs.
