### ISSUE TITLE
ERROR: Nothing PROVIDES 'kde-base-image'

### ISSUE THREAD

**Issue by outbackdingo** [schnitzeltony/meta-mortsgna#16]
git log
commit 9ebd223d473c6dfdcf0d79a290ae9f999a6e4d42 (HEAD -> master, origin/master, origin/HEAD)
Author: Andreas Müller <schnitzeltony@gmail.com>
Date:   Wed Jun 3 22:54:33 2020 +0200

cat conf/bblayers.conf 
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/dingo/nvidia/poky/meta \
  /home/dingo/nvidia/poky/meta-poky \
  /home/dingo/nvidia/poky/meta-yocto-bsp \
  /home/dingo/nvidia/meta-openembedded/meta-oe \
  /home/dingo/nvidia/meta-openembedded/meta-multimedia \
  /home/dingo/nvidia/meta-openembedded/meta-networking \
  /home/dingo/nvidia/meta-openembedded/meta-filesystems \
  /home/dingo/nvidia/meta-openembedded/meta-perl \
  /home/dingo/nvidia/meta-openembedded/meta-python \
  /home/dingo/nvidia/meta-openembedded/meta-gnome \
  /home/dingo/nvidia/meta-openembedded/meta-xfce \
  /home/dingo/nvidia/meta-virtualization \
  /home/dingo/nvidia/meta-tegra \
  /home/dingo/nvidia/meta-mortsgna \
  /home/dingo/nvidia/meta-clang \
  /home/dingo/nvidia/meta-qt5 \
  /home/dingo/nvidia/meta-qt5-extra \
  "
# This sets the default machine to be qemux86-64 if no other machine is selected:
#MACHINE ??= "qemux86-64"
MACHINE = "jetson-xavier-nx-devkit"
LICENSE_FLAGS_WHITELIST = "commercial"
IMAGE_CLASSES += "image_types_tegra"
IMAGE_FSTYPES = "tegraflash"
LICENSE_FLAGS_WHITELIST = "commercial_ffmpeg commercial_faad2 commercial_x264 commercial_gstreamer1.0-plugins-ugly"
LICENSE_FLAGS_WHITELIST_append = " commercial_faad2 commercial_libomxil commercial_vlc commercial_mpeg2dec commercial_gstreamer1.0-omx commercial_gstreamer1.0-omx-tegra commercial_gstreamer1.0-libav"
CORE_IMAGE_EXTRA_INSTALL += " tunctl git htop bash curl wget "

DISTRO_FEATURES_append = " l4t-usb-device-mode virtualization k8s"

NVIDIA_DEVNET_MIRROR = " file://home/dingo/nvidia/nvidia/sdkm_downloads"

DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
#INITRAMFS_IMAGE_BUNDLE=" 1"
#IMAGE_FSTYPES = "${INITRAMFS_FSTYPES}"

ENABLE_UART = "1"
IMAGE_INSTALL_append = " dtc xen zerotier mosquitto tunctl sudo wireguard-tools kubernetes nvidia-docker kernel-modules ipvsadm "
IMAGE_INSTALL_append +=" plasma-world packagegroup-core-buildessential"
INSANE_SKIP_zerotier = " already-stripped"

EXTRA_IMAGE_FEATURES += " package-management "
INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -P 4nn1343v3r root; \
                      useradd -P 4nn1343v3r dingo; \
                      useradd -P awn1x admin; \
                      usermod  -a -G sudo dingo;" 

PACKAGE_FEED_URIS = "http://repo.optimcloud.com/repo"
PACKAGE_FEED_BASE_PATHS = "rpm"
PACKAGE_FEED_ARCHS = "noarch jetson_nano_qspi_sd armv8a_tegra210 aarch64"

KERNEL_MODULE_AUTOLOAD += "xt_conntrack"
KERNEL_MODULE_AUTOLOAD += "xt_addrtype"

bitbake kde-base-image
Loading cache: 100% |##########################################################################################################################################################################################################################################################################################| Time: 0:00:00
Loaded 4356 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################################################################################################| Time: 0:00:00
Parsing of 3102 .bb files complete (3099 cached, 3 parsed). 4356 targets, 184 skipped, 0 masked, 0 errors.
ERROR: Nothing PROVIDES 'kde-base-image'
kde-base-image was skipped: 'x11-base' in IMAGE_FEATURES is not a valid image feature. Valid features: allow-empty-password allow-root-login bash-completion-pkgs dbg-pkgs debug-tweaks dev-pkgs doc doc-pkgs empty-root-password package-management post-install-logging ptest-pkgs qtcreator-debug read-only-rootfs splash src-pkgs stateless-rootfs staticdev-pkgs

**Comment by schnitzeltony** [comment]
You have two distro layers in your bblayers - that won't work: either poky or mortsgna.

* If you go poky way: Build a X11 image and add plasma-world (you append that already)
* If you go mortsgna way: build kde-base-image

When I look at the quirks you have in your configuration, I'd suggest to go poky way: the community there is wider and tegra did not test anything with mortsgna (you have packagefeeds - they definitely wont't work with mortsgna)

**Comment by outbackdingo** [comment]
okay, currently building core-image-x11 from poky ..... lets see where we get! Thanks
